# Copyright (C) 2023 Dynamic Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bump minor version

on:
  workflow_dispatch:

env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test-latest-websight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Bump version
        run: |
          git config --global user.email "github.actions@ds.pl"
          git config --global user.name "GitHub Actions"
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          ls -al ~/.ssh
          git branch feature/bump-minor-version
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT
          export CURRENT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout`
          git commit -am "Bump version to ${CURRENT_VERSION}"
          git push
          echo "Version bumped to ${CURRENT_VERSION}" >> $GITHUB_ENV
          gh pr create -B ${{ github.ref }} -H feature/bump-minor-version --message "Bump version to ${CURRENT_VERSION}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}